/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vitor
 */
public class tela_GUI extends javax.swing.JFrame {
String NotaPDT[] = new String[100];
        int NotaPRE[] = new int[100]; 
        int NotaQUANT [] = new int [100];
        int aux = 0;
        int auxsomapdt = 0;
        int auxsomatotal = 0;
    /**
     * Creates new form tela_GUI
     */
    public tela_GUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Cadastro_Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Codigo_pdt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Preco_pdt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Nome_pdt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        compraTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        carrinhoNome_pdt = new javax.swing.JTextField();
        carrinhoPreco_pdt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        carrinhoQuantidade_pdt = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jEditorPane1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setLayout(null);

        Cadastro_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço", "Código"
            }
        ));
        jScrollPane2.setViewportView(Cadastro_Table);
        if (Cadastro_Table.getColumnModel().getColumnCount() > 0) {
            Cadastro_Table.getColumnModel().getColumn(0).setHeaderValue("Nome");
            Cadastro_Table.getColumnModel().getColumn(1).setHeaderValue("Preço");
            Cadastro_Table.getColumnModel().getColumn(2).setHeaderValue("Código");
        }

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(0, 170, 800, 196);

        jLabel1.setText("Nome do produto:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 30, 110, 20);

        Codigo_pdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Codigo_pdtActionPerformed(evt);
            }
        });
        jPanel2.add(Codigo_pdt);
        Codigo_pdt.setBounds(650, 30, 120, 22);

        jLabel2.setText("Preço do produto:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(290, 30, 110, 20);

        Preco_pdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Preco_pdtActionPerformed(evt);
            }
        });
        jPanel2.add(Preco_pdt);
        Preco_pdt.setBounds(400, 30, 120, 22);

        jLabel3.setText("Código Produto:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(560, 30, 90, 20);

        Nome_pdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nome_pdtActionPerformed(evt);
            }
        });
        jPanel2.add(Nome_pdt);
        Nome_pdt.setBounds(110, 30, 120, 22);

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(350, 110, 100, 40);

        jButton5.setBackground(new java.awt.Color(204, 0, 0));
        jButton5.setText("X");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(710, 390, 90, 40);

        jTabbedPane1.addTab("Cadastrar Produto", jPanel2);

        jPanel1.setLayout(null);

        jButton1.setText("Efetuar Compra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 380, 170, 30);

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(720, 410, 90, 40);

        compraTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUTO", "PREÇO", "QUANTIDADE"
            }
        ));
        jScrollPane6.setViewportView(compraTable);

        jPanel1.add(jScrollPane6);
        jScrollPane6.setBounds(0, 140, 810, 210);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Preço:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 20, 70, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Quantidade:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(540, 20, 90, 20);

        carrinhoNome_pdt.setText("jTextField1");
        jPanel1.add(carrinhoNome_pdt);
        carrinhoNome_pdt.setBounds(120, 20, 110, 22);
        jPanel1.add(carrinhoPreco_pdt);
        carrinhoPreco_pdt.setBounds(350, 20, 130, 22);

        jButton3.setText("Adicionar ao Carrinho");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(310, 90, 180, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Produto:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 20, 90, 20);
        jPanel1.add(carrinhoQuantidade_pdt);
        carrinhoQuantidade_pdt.setBounds(640, 20, 130, 22);

        jTabbedPane1.addTab("Produto", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        setBounds(0, 0, 814, 479);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel cdtTable = (DefaultTableModel) Cadastro_Table.getModel();
        Object [] dados = {Nome_pdt.getText(), Preco_pdt.getText(), Codigo_pdt.getText()};
        cdtTable.addRow(dados);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Nome_pdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nome_pdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nome_pdtActionPerformed

    private void Preco_pdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Preco_pdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Preco_pdtActionPerformed

    private void Codigo_pdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Codigo_pdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Codigo_pdtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        String NomeCliente = JOptionPane.showInputDialog(null, "Nome do cliente:");
        String NumeroCliente = JOptionPane.showInputDialog(null, "Numero para contato");
        String CpfCliente = JOptionPane.showInputDialog(null, "CPF do cliente: ");
        String x = JOptionPane.showInputDialog(null, "Forma de Pagamento:\n1) Debito\n2) Credito\n3) Pix\n4) Dinheiro");
        int pagamento = Integer.parseInt (x);
        
        
         System.out.println("--------Mercado--------");
         
        System.out.println("NOTA FISCAL");
        
        for (int i = 0; i<100; i++){
            if (NotaPRE[i]>0){
                  
                 System.out.println("Nome do produto: "+ NotaPDT[i] + "-----Valor: R$" +NotaPRE[i] + "-----Quantidade: "+  NotaQUANT [i]);
            }      
}
     System.out.println("VALOR FINAL: " + auxsomatotal);
     System.out.println("-----------------------");
     System.out.println("DADOS DO CLIENTE:\nNome: "+ NomeCliente+"\nNumero: "+NumeroCliente+"\nCPF: "+CpfCliente);
     System.out.println("-----------------------");
     
     if (pagamento==1){
         System.out.println("Forma de pagamento: Débito");
     }else if (pagamento ==2){
         System.out.println("Forma de pagamento: Crédito");
     }else if (pagamento ==3){
         System.out.println("Forma de pagamento: Pix");
     }else if (pagamento ==4){
         System.out.println("Forma de pagamento: Dinheiro");
     }
     
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
        
       
        
        int preco =  Integer.parseInt( carrinhoPreco_pdt.getText());
        int quant = Integer.parseInt (carrinhoQuantidade_pdt.getText());
        
        NotaPDT[aux] = carrinhoNome_pdt.getText();
        NotaPRE[aux] = preco;
        NotaQUANT[aux] = quant;
        
        
        auxsomapdt = NotaPRE[aux] * NotaQUANT[aux];
        auxsomatotal = auxsomapdt + auxsomatotal ;
        JOptionPane.showConfirmDialog(null, preco + "," + quant);
        
        
        
        
        aux = aux + 1;
        
        
        
        DefaultTableModel cmpTable = (DefaultTableModel) compraTable.getModel();
        Object [] dados = {carrinhoNome_pdt.getText(), carrinhoPreco_pdt.getText(), carrinhoQuantidade_pdt.getText()};
        cmpTable.addRow(dados);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Cadastro_Table;
    private javax.swing.JTextField Codigo_pdt;
    private javax.swing.JTextField Nome_pdt;
    private javax.swing.JTextField Preco_pdt;
    private javax.swing.JTextField carrinhoNome_pdt;
    private javax.swing.JTextField carrinhoPreco_pdt;
    private javax.swing.JTextField carrinhoQuantidade_pdt;
    private javax.swing.JTable compraTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
